name: localization
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  archive: ^3.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1

flutter:
  assets:
    - assets/lang/